### ISSUE TITLE
Asda - error: Auth failed. The website is thinks this could be a bot, and is showing a Recaptch check. Try logging in yourself, and this might go away

### ISSUE THREAD

**Issue by git-creat** [paulmaunders/delivery-slot-bot#75] opened 2020-05-11 10:45 UTC
Hi, I've used the bot and it works well for Tesco, however I can't get it to work for Asda, I keep getting the following message:

> error: Auth failed. The website is thinks this could be a bot, and is showing a Recaptch check. Try logging in yourself, and this might go away

Does anyone know how to get around this?

**Comment by git-creat** [comment] 2020-05-11 10:46
I should add that I've tried logging in on a browser but the error message doesn't go away.

**Comment by andytson** [comment] 2020-05-11 10:49
closing as duplicate of #72

**Closed by andytson** 2020-05-11 10:49 UTC
